name: cipherkey_flutter
description: CipherKey rebuilt in Flutter for Android and iOS.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.4+2
  path: ^1.9.0
  path_provider: ^2.1.4
  share_plus: 10.1.4
  shared_preferences: ^2.3.2
  file_picker: 8.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
